### ISSUE TITLE
Filter sites for monosoon

### ISSUE THREAD

**Issue by klprudic** [Big-Biodiversity-Collaborative/AZNABA#2]
@BradJohnson6 filter full data set to focus on post-monsoon observations across AZ sites

**Comment by HelenIvy** [comment]
Katy suggested these two time periods: Fall: July 15 - Oct 31 (109 days)
Spring: Mar 1 - Jun 15 (107 days)

**Comment by BradJohnson6** [comment]
Created fall and spring data frames to match the above dates

**Comment by HelenIvy** [comment]
@BradJohnson6 will explain how we dealt with sites that had two samplings per year and which sites and sites/sampling times dropped as a result.

**Comment by BradJohnson6** [comment]
6/20/1982 Atascosa highlands, 6/24/1982 Ramsey Canyon, 7/5/2015 Grand Canyon north rim, 7/7/1998 Sycamore creek sampling events all removed due to not fitting in the above designated time frames

**Comment by BradJohnson6** [comment]
10/1/2011
9/30/2012
9/29/2013
9/28/2014
9/27/2015
10/2/2016
9/30/2017
9/29/2018
9/28/2019
10/4/2020
10/2/2021 Santa Rita mountains sampling events removed as they are the second event for each year

**Comment by BradJohnson6** [comment]
Commit fc06aa5 creates fall and spring data frames which are ready for analysis
